name: Ruby

on:
  push:
    branches: [master]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec jekyll build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{secrets.learn-devops}}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./_test
      with:
      username: "hoochanlon"
      useremail: "hoochanlon@outlook.com"